nodeLinker: node-modules

plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-outdated.cjs
      spec: 'https://mskelton.dev/yarn-outdated/v2'
    - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
      spec: '@yarnpkg/plugin-typescript'
