services:
    coinage-db:
        restart: unless-stopped
        image: mysql
        env_file:
            - ./.env
        ports:
            - 3306:3306
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "--password=$MYSQL_ROOT_PASSWORD"]
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 10s
    coinage-api:
        build:
            context: .
            dockerfile: docker/api.Dockerfile
        image: coinage-api
        env_file:
            - ./.env
        environment:
            MYSQL_HOST: coinage-db
        ports:
            - ${COINAGE_API_PORT:-8333}:8333
        depends_on:
            coinage-db:
                condition: service_healthy
    coinage-webapp:
        build:
            context: .
            dockerfile: docker/webapp.Dockerfile
        image: coinage-webapp
        ports:
            - ${COINAGE_WEBAPP_PORT:-8100}:8100
        depends_on:
            - coinage-api
