version: '3'
services:
    coinage-db:
        restart: unless-stopped
        image: mysql
        env_file:
            - ./.env
        ports:
            - 33060:3306
    coinage-api:
        build:
            context: .
            dockerfile: api.Dockerfile
        image: coinage-api
        environment:
            MYSQL_HOST: coinage-db
        env_file:
            - ./.env
        ports:
            - 3333:3333
        depends_on:
            - coinage-db
    coinage-webapp:
        build:
            context: .
            dockerfile: webapp.Dockerfile
        image: coinage-webapp
        ports:
            - 80:80
