version: '3'
services:
    coinage-db:
        image: mysql
        env_file:
            - ./.env
        ports:
            - 3306:3306
    coinage-api:
        image: coinage-api
        environment:
            MYSQL_HOST: coinage-db
        env_file:
            - ./.env
        ports:
            - 3333:3333
    coinage-webapp:
        image: coinage-webapp
        ports:
            - 80:80
